### ISSUE TITLE
incorrect version number in getting started guide

### ISSUE THREAD

**Issue by sapiens-sapide** [cityzendata/warp10-platform#55]
Hello,
I'm diving into warp10 for the first time. I followed your getting started guide, but the version number given in that guide (1.0.5) mismatch the version cloned from github (1.0.6).
Therefore, the worf.sh script fails to start the worf console.

Regards,
Stan.

**Comment by slambour** [comment]
Hello, 
The 1.0.6 version is the last published version of Warp10 platform, the getting started guide is now up to date. 
Please wipe your local directory /var/warp10 before build and launch docker again with the same version name, there is an issue on that, it will be fixed with the next release 1.0.7.

If you still have a problems with Worf, please feel free to join our Google group for assistance. https://groups.google.com/forum/#!forum/warp10-users

Regards, 
Sébastien
