### ISSUE TITLE
Issue with TIMECLIP

### ISSUE THREAD

**Issue by Alkorin** [cityzendata/warp10-platform#88]
On a Timecliped-Bucketized-gts, `FILLVALUE` will insert values outside of the clip's range: [(Script)](https://home.cityzendata.net/quantum/#/warpscript/TkVXR1RTIAo1MDAgIE5hTiBOYU4gTmFOICA2IEFERFZBTFVFCjExMDAgIE5hTiBOYU4gTmFOIDEwIEFERFZBTFVFCjEyMDAgIE5hTiBOYU4gTmFOICA5IEFERFZBTFVFCjEzMDAgIE5hTiBOYU4gTmFOICA4IEFERFZBTFVFClsgU1dBUCBidWNrZXRpemVyLmNvdW50IDAgNSAwIF0gQlVDS0VUSVpFCjEyNTAgMjUwIFRJTUVDTElQClsgU1dBUCBdClsgTmFOIE5hTiBOYU4gMCBdIEZJTExWQUxVRQ%3D%3D/eyJ1cmwiOiJodHRwczovL3dhcnAuY2l0eXplbmRhdGEubmV0L2FwaS92MCIsImhlYWRlck5hbWUiOiJYLUNpdHl6ZW5EYXRhIn0%3D)

Workaround: reclip after `FILLVALUE` [(Script)](https://home.cityzendata.net/quantum/#/warpscript/TkVXR1RTIAo1MDAgIE5hTiBOYU4gTmFOICA2IEFERFZBTFVFCjExMDAgIE5hTiBOYU4gTmFOIDEwIEFERFZBTFVFCjEyMDAgIE5hTiBOYU4gTmFOICA5IEFERFZBTFVFCjEzMDAgIE5hTiBOYU4gTmFOICA4IEFERFZBTFVFClsgU1dBUCBidWNrZXRpemVyLmNvdW50IDAgNSAwIF0gQlVDS0VUSVpFCjEyNTAgMjUwIFRJTUVDTElQClsgU1dBUCBdClsgTmFOIE5hTiBOYU4gMCBdIEZJTExWQUxVRQoxMjUwIDI1MCBUSU1FQ0xJUA%3D%3D/eyJ1cmwiOiJodHRwczovL3dhcnAuY2l0eXplbmRhdGEubmV0L2FwaS92MCIsImhlYWRlck5hbWUiOiJYLUNpdHl6ZW5EYXRhIn0%3D). Is it the expected behaviour ?

**Comment by hbs** [comment]
TIMECLIP will limit the datapoints to those ticks within the specified range. If the GTS is bucketized it will retain its original bucketization parameters (lastbucket, bucketspan, bucketcount), so my guess is that your GTS was bucketized then timeclipped instead of timeclipped then bucketized.

If you want to limit the buckets to those within a given range simply do a BUCKETIZE with the correct parameters, the range will be [ lastbuccket - bucketcount * bucketspan + 1, lastbucket ].
